name: dbt CI/CD for Snowflake

on:
  push:
    branches: [main]          # Auto deploy to DEV
  pull_request:
    branches: [main]          # Trigger PR for manual approval before PROD
  workflow_dispatch:          # Allow manual trigger for PROD

jobs:
  run-dbt-dev:
    name: Run dbt in Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          snowflake_project:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: TEWNAEX-QQ42202
                user: ${DBT_USER}
                password: ${DBT_PASSWORD}
                role: ACCOUNTADMIN
                database: PRANJAL
                warehouse: COMPUTE_WH
                schema: PUBLIC
                threads: 1
                client_session_keep_alive: false
              prod:
                type: snowflake
                account: TEWNAEX-QQ42202
                user: ${DBT_USER}
                password: ${DBT_PASSWORD}
                role: ACCOUNTADMIN
                database: PRANJAL_PROD
                warehouse: COMPUTE_WH
                schema: PUBLIC
                threads: 1
                client_session_keep_alive: false
          EOF
        env:
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}

      - name: Run dbt models in DEV
        run: |
          dbt deps
          dbt run --target dev

  deploy-to-prod:
    name: Deploy to Prod (Manual or PR Merge)
    needs: run-dbt-dev
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          snowflake_project:
            target: prod
            outputs:
              dev:
                type: snowflake
                account: TEWNAEX-QQ42202
                user: ${DBT_USER}
                password: ${DBT_PASSWORD}
                role: ACCOUNTADMIN
                database: PRANJAL
                warehouse: COMPUTE_WH
                schema: PUBLIC
                threads: 1
                client_session_keep_alive: false
              prod:
                type: snowflake
                account: TEWNAEX-QQ42202
                user: ${DBT_USER}
                password: ${DBT_PASSWORD}
                role: ACCOUNTADMIN
                database: PRANJAL_PROD
                warehouse: COMPUTE_WH
                schema: PUBLIC
                threads: 1
                client_session_keep_alive: false
          EOF
        env:
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}

      - name: Run dbt models in PROD
        run: |
          dbt deps
          dbt run --target prod
