name: dbt CI/CD for Snowflake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          snowflake_project:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: TEWNAEX-QQ42202
                user: ${{ secrets.DBT_USER }}
                password: ${{ secrets.DBT_PASSWORD }}
                role: ACCOUNTADMIN
                database: PRANJAL
                warehouse: COMPUTE_WH
                schema: PUBLIC
                threads: 1
                client_session_keep_alive: false
          EOF

      - name: Run dbt models in DEV
        run: |
          dbt deps
          dbt run --target dev
